#!/bin/bash
#

cd /export/sunsite/users/gutenbackend/converter
~/.local/bin/pipenv shell

TMP=$PRIVATE/tmp/rdf
mkdir -p $TMP

# cd $PUBLIC


DAYOFWEEK=$(date +"%u")
if [ "${DAYOFWEEK}" -eq 4 ]; then
  # run once a week
  header ebookconverter
  ebookconverter -v -v --range=1- --build=rdf --jobs=100 --pidfile=/tmp/rdfbuild.pid
fi

header "getting list of rdf files"

find ~/cache/epub -name '*.delete' -prune -o -name 'DELETE*' -prune -o -name '*.rdf' -print | sort -n > $TMP/rdf-files.txt
echo -n "count: "
wc -l < $TMP/rdf-files.txt

header "ones with mod-time in the last 24 hours:"
find ~/cache/epub -name '*.rdf' -mtime -1 -print > $TMP/recent
n_recent_files=`wc -l < $TMP/recent`
if [ $n_recent_files -ge 100 ]; then
    echo "(Too many files to list: $n_recent_files)"
else
    sort $TMP/recent
fi

header "making tarball of rdf files"
tar -cf $TMP/rdf-files.tar -T $TMP/rdf-files.txt

cd $TMP

header "zip & bzip the tarball"
zip rdf-files.tar.zip rdf-files.tar
bzip2 -kf rdf-files.tar
mv -f rdf-files.tar.* $FEEDS/

rm $TMP/*
