#!/bin/bash
#
# Making changes to the original cron-dopush-latesttittles.sh script to point to gutenberg-app1 for getting the latest covers with the updated design and running a jekyll build for reflecting the changes. The latest titles are generated by the latest_covers_template.html in the _includes directory.

#####
# Changelog
# 20200429 - initial version (hely)
# 20200529 - fix issue with incomplete output (gbnewby)

# Set up our environment:
cd /export/sunsite/users/gutenbackend/ebookconverter
. ./.env

GREP=/usr/bin/grep
SEQ=/usr/bin/seq
SED=/usr/bin/sed
CP=/usr/bin/cp
# Where to build (we might need to have multiple dev v. production locations
# in the future)
BUILD=/public/vhost/g/gutenberg/gutenbergsite

# Fetch input, the latest covers:
# wget -O ${BUILD}/_includes/latest_covers.html "http://gutenberg-app1:8000/covers/small/latest/10"
# This is going to dev:
wget -O ${BUILD}/_includes/latest_covers.html "http://[2610:28:3090:3001:0:dead:cafe:100]:8000/covers/small/latest/10"

# Write to here:
#OUTPUT=${BUILD}/_includes/final_covers.html

# These commands are run at the end of cron-dopush.sh, which will
# normally the run this file to transform the latest covers:

# This deploys the new content. Any errors will be returned; otherwise
# output is quelled:
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" 

# Deploy the new content:
cd ${BUILD}
jekyll build > /dev/null

exit
