#!/public/vhost/g/gutenberg/local/bin/python3.6
#  -*- mode: python; indent-tabs-mode: nil; -*- coding: UTF8 -*-

"""

ebookconverter script

This script starts epubmaker.

"""

from ebookconverter import EbookConverter

EbookConverter.main ()
