#!/public/vhost/g/gutenberg/local/bin/python3.6
#  -*- mode: python; indent-tabs-mode: nil; -*- coding: iso-8859-1 -*-

"""

fileinfo script

Distributable under the GNU General Public License Version 3 or newer.

This script runs fileinfo.

"""

from ebookconverter import FileInfo

FileInfo.main()
