#!/bin/bash
# 

#
# pgmarc
#
# Distributable under the GNU General Public License Version 3 or newer.
#
# This script runs PGmarc., zips the resulting files
#

cd ~/ebookconverter
. ./.env

~/.local/bin/pipenv run python -m ebookconverter.PGMarc 0 80000

zip -j $FEEDS/pgmarc.xml.zip $FEEDS/pgmarc.xml
zip -j $FEEDS/pgmarc.mrc.zip $FEEDS/pgmarc.mrc