#!/public/vhost/g/gutenberg/local/bin/python3.6
#  -*- mode: python; indent-tabs-mode: nil; -*- coding: UTF8 -*-

"""

pgmarc script

Distributable under the GNU General Public License Version 3 or newer.

This script runs fileinfo.

"""

from ebookconverter import PGMarc

PGMarc.main()
